### ISSUE TITLE
Irrecoverable files from smurf-epics-slac

### ISSUE THREAD

**Issue by agustiner** [slaclab/smurf-tpg-ioc-docker#3]
Problem

We're using the R1.7.3-1.3.0 image for testing the SMuRF timing system, and need to update the TPG software. Trying to build the R1.7.3-1.3.0 image again fails because the underlying image, smurf-epics-slac, is outdated. The smurf-epics-slac image depends on files specifically taken from somewhere in the internal AFS filesystem at SLAC. There is no way to build smurf-epics-slac without these files.

- smurf-epics-slac: https://github.com/jesusvasquez333/smurf-epics-slac
- internal files: https://github.com/jesusvasquez333/smurf-epics-slac/blob/master/Dockerfile#L38

Possible solutions

- Don't update the docker image. We're going with this option for now.
- Find the directory that Jesus was cd'd into to compile these files again. Not sure how likely this is.
- Extract the source files from the old image and keep them in Git. Strange, but doable.
- Other solutions...

**Comment by marciodo** [comment]
Problem 1: the CentOS default repo used in the last version of the base Docker smurf-epics-slac became available since then. Solution: build smurf-epics-slac with 

`RUN curl https://www.getpagespeed.com/files/centos6-eol.repo --output /etc/yum.repos.d/CentOS-Base.repo`

Problem 2: the provided TPG IOC is a copy of a SLAC IOC manually adapted for this use case. Automation should be done here otherwise the maintenance will be a nightmare.

Problem 3: EPICS base and modules used to build smurf-epics-slac are manually tar.gz to be copied to the container. Also, automation is needed in this process.

**Comment by marciodo** [comment]
I've imported smurf-epics-slac from Jesus account to slaclab: https://github.com/slaclab/smurf-epics-slac

**Comment by jesusvasquez333** [comment]
If for some reason you need to update the base epics image (I assume you might need newer epics modules and/or newer packages?) then you will need to take those packages/modules from the SLAC AFS-based repositories. 

At the time I build this image there was not way to access AFS space from a server with the Docker engine. So I had to move the packages are tarball as described here. The same can be done a again; all the packages/modules are available unser $PACKAGE_TOP and $EPICS_MODULES_TOP.

Although currently there are new centos7 servers at SLAC with access to AFS and which support the Docker engine. So that would be a more convenient way to move forward. @marciodo has done great progress in this path so he would know how to beat proceed.

If you have questions please feel free to reach to me.

**Comment by jesusvasquez333** [comment]
If it is helpful, the original files I used to build this docker images are still available here:
```bash
/afs/slac/g/controls/development/users/jvasquez/backups/afs/iocTop/jvasquez/smurf/dockers/epics_slac
```

```bash
$ tree .
.
├── Dockerfile
├── R3.15.5-1.0.tar.gz
├── build.sh
├── modules
│   ├── RELEASE_SITE
│   ├── asyn
│   │   ├── R4.31-0.1.0
│   │   │   └── asyn
│   │   │       └── asynPortDriver
│   │   │           └── exceptions
│   │   └── R4.31-0.1.0.tar.gz
│   ├── autosave
│   │   ├── R5.7.1-3.2.0.tar.gz
│   │   └── R5.8-1.0.0.tar.gz
│   ├── bsaDriver
│   │   └── R1.5.0.tar.gz
│   ├── caPutLog
│   │   └── R3.5-0.1.0.tar.gz
│   ├── calc
│   │   └── R3.6.1-0.1.0.tar.gz
│   ├── crossbarControl
│   │   └── R1.0.4.tar.gz
│   ├── iocAdmin
│   │   ├── R3.1.15-1.0.0.tar.gz
│   │   └── R3.1.15-1.1.0.tar.gz
│   ├── miscUtils
│   │   └── R2.2.5.tar.gz
│   ├── normativeTypesCPP
│   │   └── R5.2.0-0.0.1.tar.gz
│   ├── pvAccessCPP
│   │   └── R6.0.0-0.3.0.tar.gz
│   ├── pvDataCPP
│   │   └── R7.0.0-0.0.1.tar.gz
│   ├── pvDatabaseCPP
│   │   └── R4.3.0-0.0.3.tar.gz
│   ├── pva2pva
│   │   └── R1.0.0-0.3.1.tar.gz
│   ├── seq
│   │   ├── R2.2.4-1.0.tar.gz
│   │   └── R2.2.4-1.1.tar.gz
│   ├── sscan
│   │   └── R2.10.2-0.1.0.tar.gz
│   └── yamlLoader
│       └── R1.1.0.tar.gz
└── packages
    ├── boost
    │   └── 1.63.0.tar.gz
    ├── cpsw
    │   └── framework
    │       └── R3.6.4.tar.gz
    ├── pcre
    │   └── 8.37.tar.gz
    ├── timing
    │   ├── bsa
    │   │   ├── R1.1.0.tar.gz
    │   │   └── R1.1.1.tar.gz
    │   └── tpg
    │       └── R1.3.2.tar.gz
    └── yaml-cpp
        └── yaml-cpp-0.5.3.tar.gz

30 directories, 30 files
```

**Comment by agustiner** [comment]
This is fixed thanks to Marcio. For now, new versions of this docker image are not needed because Kukhee managed to program the current docker image via EPICS commands. Closing for now.
